# CloudCannon Configuration
collections_config:
  videos:
    name: "Movies List"
    path: "_data/videos.json"
    icon: "movie"
    allow_create: true
    allow_delete: true

# Form ke Boxes yahan se bante hain
_inputs:
  title:
    type: text
    label: "Movie ka Naam"
  video_url:
    type: text
    label: "Download Link (URL)"