collections_config:
  videos:
    name: "Movies List"
    path: "_data/videos.json"
    parser: "json"
    icon: "movie"

_inputs:
  title:
    type: text
    label: "Movie ka Naam"
  video_url:
    type: text
    label: "Download Link (URL)"