# CloudCannon Configuration
collections_config:
  videos:
    name: "Movies List"
    path: "_data/videos.json"
    icon: "movie"
    allow_create: true
    allow_delete: true

# Yahan se aap Labels (Naam) badal sakte hain
_inputs:
  title:
    type: text
    label: "Movie ka Naam (Title)"  # Ye label box ke upar dikhega
  video_url:
    type: text
    label: "Video Download Link"    # Ye label link wale box ke liye hai
  thumbnail:
    type: image
    label: "Poster Image (URL)"     # Ye poster ke liye label hai